---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      no-shadow-restricted-names:
        enabled: false
      max-statements:
        enabled: false
      no-cond-assign:
        enabled: false
      no-unused-expressions:
        enabled: false
      callback-return:
        enabled: false
      complexity:
        enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: false
ratings:
  paths:
  - "src/**.js"
exclude_paths:
- dist/
